### ISSUE TITLE
Youtube-Upload documentation says one minute.

### ISSUE THREAD

**Issue by tjsavage** [Polymer/polymer-analyzer#132]
_From @GanadiniAkshay on June 8, 2015 7:52_

The google-youtube-upload component's documentation on the polymer-project website says "one minute".

_Copied from original issue: Polymer/polymer#1777_

**Comment by tjsavage** [comment]
_From @ebidel on June 8, 2015 15:1_

Page?

**Comment by tjsavage** [comment]
_From @GanadiniAkshay on June 8, 2015 15:26_

https://elements.polymer-project.org/elements/google-youtube-upload

**Comment by tjsavage** [comment]
_From @kevinpschaaf on June 8, 2015 16:32_

This issue tracker is for the Polymer core library, not elements built with it. We'll get this moved to an appropriate spot.

**Comment by tjsavage** [comment]
_From @GanadiniAkshay on June 8, 2015 16:33_

Sorry didn't notice.

**Comment by tjsavage** [comment]
This is interesting - I think this might be an issue with hydrolysis. Moving to that repo.

**Comment by ebidel** [comment]
This has been fixed on youtube-upload (https://github.com/GoogleWebComponents/google-youtube-upload/pull/8) but we should fix the hydrolysis bug.

**Comment by rictic** [comment]
Closing because it's not clear what the problem was or what the state of the google-youtube-upload element was that triggered the hydrolysis bug. Feel free to reopen with details.
