### ISSUE TITLE
Seems to not pick up docs for non-standard element definitions

### ISSUE THREAD

**Issue by tjsavage** [Polymer/polymer-analyzer#142]
For example:

https://github.com/PolymerElements/iron-icons/blob/master/iron-icons.html

**Comment by garlicnation** [comment]
Iron-icons isn't an element, right? We could still structure its data like an element, but it needs some kind of `type` and to have its non-element status reflected in iron-component-page and elements.polymer-project.org.

**Comment by arthurevans** [comment]
I think it also depends on hydrolysis parsing comments in files that it doesn't recognize as a element definitions or behaviors, which may or may not be part of #136. At any rate -- we really need to get these working.

**Comment by rictic** [comment]
This looks working now.
