### ISSUE TITLE
Getter reported as method

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/polymer-analyzer#144]
[Polymer.IronSelectableBehavior's documentation](https://elements.polymer-project.org/elements/iron-selector?active=Polymer.IronSelectableBehavior) lists `items()` as a method, failing to mention that it's actually a getter -- so it can't be called like a method.

Hydrolysis should identify getters/setters/getter+setters and report them as such, right?

**Comment by robrez** [comment]
+1 Came to report this... I noticed it in the paper-header-panel docs...

![hydrolysis_1](https://cloud.githubusercontent.com/assets/1993389/10177917/620560e6-66c2-11e5-92bb-7dc562135348.png)

![hydrolysis_2](https://cloud.githubusercontent.com/assets/1993389/10177920/68fc312c-66c2-11e5-923e-548b48ab75fb.png)

**Comment by garlicnation** [comment]
@blasten This is what you had talked to me about today.

We should have a resolution soon.

**Comment by rictic** [comment]
Looks like this was fixed a while ago
