### ISSUE TITLE
Option to exclude

### ISSUE THREAD

**Issue by srikkbhat** [Polymer/polymer-analyzer#210]
I have built [progressive-vulcans](https://github.com/srikkbhat/progressive-vulcans) to have incremental vulcanized files. I use hydrolysis to identify shared elements and vulcanize to vulcanize shared elements.

There are certain scenario where I want to exclude elements from hydrolysis and vulcanize. I am able to exclude the elements from vulcanize using `--strip-excludes` option. However hydrolysis does not provide such option.  So there is a difference between elements that are vulcanized and the elements that my code thinks are vulcanized.

Would like to have the something similar to `--strip-excludes` option available in hydrolysis too.

**Comment by rictic** [comment]
You should be able to post process the output of the analyzer to exclude urls/documents that you would like to leave out.

Can you expand on your use case?

**Comment by srikkbhat** [comment]
Thanks for your response. I'll take a look at it.
I am no longer actively developing my tool. Also the polymer team has built alternatives over time. So closing this issue.
