### ISSUE TITLE
Handle ES6 source

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-analyzer#221]
See https://github.com/PolymerElements/iron-component-page/issues/35

**Comment by jarrodek** [comment]
I dealing with this issue right now. I've created some components according to the article https://www.polymer-project.org/1.0/articles/es6.html and right now Polylint and my custom task in gulp do not work with my project.
Waiting for an update.

**Comment by klebba** [comment]
Is the aim to address all ES6 classes, or only those used to create a Polymer component?

**Comment by mbana** [comment]
Hello All, does this work? The official documentation, https://www.polymer-project.org/1.0/articles/es6.html, says it does. If it doesn't, could someone please highlight that it doesn't. I fear people will spend time looking at their non-faulty code wondering why it doesn't.

**Comment by SofianHn** [comment]
any update here? this really blocks ES6 adoption :S

**Comment by bastiion** [comment]
I really need a fix for this. Used ES6 in about 30 components and now I recognize my project does not build for production. Vulcanize silently fails and I this is due to hydrolysis can't parse my elements.

**Comment by RoXuS** [comment]
@bastiion with this PR #244, the ES6 elements can be displayed through an `iron-component-page`, could you tell me if the vulcanize is ok too ?

**Comment by drwaky** [comment]
+1 The same problem, any update? :(

**Comment by bastiion** [comment]
@RoXuS with the current master branch of hydrolysis vulcanize runs well. Sorry for such a long time of silence, but I was very busy in my project.
Even doc-page generation works now using an `iron-componnt-page`, with the drawback of not using behaviours in "inconvenient" ways.
Debugging Hydrolysis always makes me ask... 
What the hell is it necessary to parse the whole JavaScript source tree, relying on strict codestyle, rather than introduce a couple of comment macros?

**Comment by bastiion** [comment]
There are other things not kosher in generating the doc. If there are multiple classes within the document, hydrolysis finds them as if they are elements, even though they are just declared classes living in the same scope as the elements class.
For the behavior bug I opened a new issue #251

**Comment by rictic** [comment]
We now handle ES6 source. Still growing our library of ES6 expressions that we support. Please file bugs with code that should work but isn't!

**Comment by bedeoverend** [comment]
@rictic is there a place that documents / at least lists, the ES6 expressions and how they are analysed?

**Comment by rictic** [comment]
Yeah, check out the test/static for a few examples.
