### ISSUE TITLE
How to pass html instead of path to an element ? 

### ISSUE THREAD

**Issue by aruntk** [Polymer/polymer-analyzer#245]
I'm building a compiler package for polymer in meteor. https://github.com/meteorwebcomponents/synthesis . I'm now using parse5 to parse through html files. In meteor compilers we get html contents of the files as input. Is it possible to use hydrolysis with html as argument instead of file path.?

**Comment by rictic** [comment]
You could provide your own url-loader that knows how to load your files.

e.g.

```javascript
myLoader.resolveThisFileAs('some/fake/path', htmlContents);
```

Then ask hydrolysis to load `some/fake/path`


In the 2.0 branch I've got a PR upcoming that allows you to specify the contents of a path.
