### ISSUE TITLE
can I get *all* dependencies of a file?

### ISSUE THREAD

**Issue by fiws** [Polymer/polymer-analyzer#246]
I think there could be better documentation for this. But if there already is and I'm just not finding it, I would be very thankful if you could point me in the right direction.

I am currently trying it like this:
```
hyd.Analyzer.analyze('./some-element.htmll')
  .then((analyzer) => {
     analyzer._getDependencies('./some-element.html').then((deps) => console.log(deps));
  });

```
That way I'm getting *some* dependencies, but not all. Stuff like `polymer.html` is missing

**Comment by fiws** [comment]
Ok so i found a solution:
```
hyd.Analyzer.analyze('./some-element.htmll', { filter: () => false }) 
// ...
```

there also is https://github.com/PolymerLabs/web-component-deps which does this, but it has no doc at all. Thats where i found the filter thing though.

I'll leave this open if you want to do any doc on it. I guess it already is in the API.md but I had a lot of trouble finding it. If you don't plan to change that maybe just add a demo for that use case?
You can close it otherwise as I solved my problem :)

**Comment by rictic** [comment]
Glad you got a solution. This API is changing with 2.0 as well to be clearer and more powerful.
