### ISSUE TITLE
in-browser example?

### ISSUE THREAD

**Issue by mbana** [Polymer/polymer-analyzer#253]
Hi,
Just wondering why this can't be run via a HTML Import, say, instead of WCT. I ask because WCT can run directly without npm.
I honestly think this will help adoption.

**Comment by rictic** [comment]
I'm not sure I understand your question.  Hydrolysis on master does run in the browser, and powers iron-component-page.

Can you expand on what you're trying to do and what problems you're running into doing it?

**Comment by mbana** [comment]
e.g., demo/demo.html how does one view that?
there really needs to be a minimal working example that just runs.

**Comment by rictic** [comment]
We're currently focused on a big expansion of the capabilities of the analyzer (née hydrolysis), focusing on use from node.

I'll leave this bug open to be sure that once we've got a browser version running again we'll be sure to have an easy to use example.

**Comment by marcus7777** [comment]
I was using it to do code completion in my online editor looking forward to seeing it working again in the browser.

**Comment by rictic** [comment]
Oh, awesome! I expect you'll be very pleased with where the v2 branch is going then, it's designed to run much faster and more incrementally, as well as doing a much better job of exposing the info that's interesting to editors.

Until 2.0 is ready you can take a look at [iron-component-page](https://github.com/PolymerElements/iron-component-page/blob/master/iron-component-page.html#L23) for an example of using v1 in the browser. We have a browserified bundle published on bower.

**Comment by marcus7777** [comment]
That's so cool awesome great yes I went from iron-component-page. Was just trying to run everything on master, to see whether they all work together. But seeing as this has changed it's name I'll be able to have a copy of it separate. I presume [this](https://github.com/PolymerElements/iron-component-page/blob/master/bower.json#L20) is how to get the browserify version?

**Comment by rictic** [comment]
Yep, that'll do it! Or just `bower install Polymer/hydrolysis`
