### ISSUE TITLE
Analyze hot-table not parsing the properties

### ISSUE THREAD

**Issue by rakesh-roshan** [Polymer/polymer-analyzer#288]
I am using analyzer to parse https://github.com/handsontable/hot-table/blob/develop/src/hot-table.html

but the properties is not being parsed correctly.
In this case the properties value is set dynamically. In all examples, I saw that properties are declared static. Is it not possible to analyze dynamic properties?

**Comment by rictic** [comment]
You're not kidding about dynamic! For anyone – even a human expert – to analyze that we'd need to know the runtime values of `Handsontable.DefaultSettings`, the return value of `Handsontable.hooks.getRegistered()`.

The analyzer operates based on source code, not runtime values. It can handle some degree of dynamism, but this is well beyond its current or likely future capabilities.

**Comment by rictic** [comment]
For projects like this one that are highly dynamic what we'd suggest instead would be comment based annotations, either manually written or generated, to indicate the properties and their types and attributes to the analyzer.
