### ISSUE TITLE
Are line & column numbers 0-indexed? 1-indexed?

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/polymer-analyzer#332]
This is the type definition for position:

```
export interface Position {
  /** The line number, starting from zero. */
  line: number;
  /** The column offset within the line, starting from zero. */
  column: number;
}
```

However, most (all?) text editors treat line numbers and column numbers as starting from one. This mismatch makes reporting errors difficult, since they will all be off by one (see https://github.com/Polymer/polymer-analyzer/blob/master/src/test/analyzer_test.ts#L103).

I'm opening this issue to discuss. Can we change our internal logic to treat lines and columns as 1-indexed? Or should we account for this as consumers of analyzed documents (ex: handle in `WarningPrinter`)?

/cc @rictic @justinfagnani

**Comment by rictic** [comment]
IMO data structures should be indexed by zero, but in UI it can make sense to index by one. VS Code and Atom both follow convention as well.

**Comment by FredKSchott** [comment]
I didn't know VS Code & Atom already accounted for this, that makes sense. Sounds like you've already given this some thought :)

@rictic Is this documented anywhere? Otherwise I'll add a comment on the `SourceRange` definition.

**Comment by rictic** [comment]
I don't think it is, a comment on source range makes sense.
