### ISSUE TITLE
[2.0.0-alpha] Need a feature to represent and destructure polymer binding expressions

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-analyzer#351]
Linter is implementing some string matching to identify and parse these, but It would be best for Analyzer to identify all the `[[something]]`/`{{something}}` binding expressions as features.  Adding this as a TODO.

**Comment by rictic** [comment]
+1

**Comment by rictic** [comment]
(p0 not because it's urgent but because it's blocking a lot of linter features, and we're likely to work on it soon)

**Comment by TimvdLippe** [comment]
I suppose this has been implemented already and can be closed?

**Comment by rictic** [comment]
oh, yep!
