### ISSUE TITLE
analyze bad attributes in polymer element declaration

### ISSUE THREAD

**Issue by jay8t6** [Polymer/polymer-analyzer#364]
analyze bad attributes in polymer element declaration - this could be a really useful feature in the editor plugins.

```
<element 
  string-only-prop="[[booleanProp]]"  -- wrong type
  non-existent-prop="value" -- property doesnt exist>
</element>
```

**Comment by TimvdLippe** [comment]
I think this will be handled by https://github.com/Polymer/polymer-linter which is integrated in the editor-service for the editor plugins.

**Comment by rictic** [comment]
Thanks for filing this issue! Moved to two different polymer-linter feature requests
