### ISSUE TITLE
When a dependency of a Document changes, we must remove that Document from the cache.

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-analyzer#369]
Suppose `a`, `b`, and `c` are documents, an `a` imports `b`, and `b` imports `c`. If you call `analyzer.analyze('a')`, then we will resolve and cache all three. 

If you then call `analyzer.analyzer('c', 'new contents')` then we must remove `a` and `b` from the `Document` cache, as they must be re-resolved.

**Comment by TimvdLippe** [comment]
I think this is fixed in #394 but not autoclosed as it wasnt correctly referenced in the PR description

**Comment by rictic** [comment]
Thanks Tim!
