### ISSUE TITLE
Discover pseudo elements

### ISSUE THREAD

**Issue by MaKleSoft** [Polymer/polymer-analyzer#377]
Hydrolysis did this so I'm assuming this will be supported by polymer-analyzer as well? Just checking.

**Comment by rictic** [comment]
Yep! We do appear to be discovering the pseudo elements in polymer core. Please file a bug if you see a pseudo element that we're not matching correctly.

**Comment by MaKleSoft** [comment]
Sorry, I just realised the term 'pseudo element' is very ambiguous. What I mean is element descriptions for elements that aren't actually registered anywhere via the `@pseudoElement` tag (hence 'pseudo elements'). `iron-icons` uses this  for example: https://github.com/PolymerElements/iron-icons/blob/master/iron-icons.html#L36

There is also a related issue but its from a while back: https://github.com/Polymer/polymer-analyzer/issues/187

**Comment by rictic** [comment]
I see, gotcha. Copying your comment over to #187, let's use that as the canonical bug.

**Comment by MaKleSoft** [comment]
Cool, thx
