### ISSUE TITLE
Circular imports result in analyze promise never being resolved nor rejected

### ISSUE THREAD

**Issue by MaKleSoft** [Polymer/polymer-analyzer#388]
Title says it all. Seems circular imports result in a stalemate situation where two promises wait for each other to be resolved/rejected which means neither ever are.

**Comment by MaKleSoft** [comment]
Something to think about:

- Should circular imports be considered an error condition? Can't find anything in the spec about this but it seems like chrome is least gracefully handling them.

- Should the analyzer try to resolve circular imports or bail out when it detects them? In any case, it's definitely worth creating a warning.

**Comment by justinfagnani** [comment]
Thanks for figuring this out. Our circular import handling is definitely not complete.

Circular imports work in HTML Imports, and ES6 modules (though there are caveats around circular dependencies for exports within those graphs), so we'll support them in the analyzer.

**Comment by rictic** [comment]
Arg, I didn't notice that you'd assigned yourself to this issue, sorry about that, hope I didn't preempt what you were working on.
