### ISSUE TITLE
typings and main.d.ts file issue

### ISSUE THREAD

**Issue by kunal2u** [Polymer/polymer-analyzer#422]
I have used hydrolysis 1.24.0 . Currently when I compile my project I get an error that typings\main.d.ts file not found. This entry is listed in tsconfig.json filesGlob and files properties. From where it will generate typings folder and main.d.ts file ? I also have typings.json which has listed following ambient dependecies
"node":"github:DefinitelyTyped/DefinitelyTyped/node/node.d.ts#fc341765ebbb04b7109981a25dced01f488f4d94".
Also in .npmignore in the same folder I have entry for node_modules, bower_components and typings/ . 
bower.json has entry for hydrolysis and devDependencies for polymer, webcomponentjs, web-compnent-tester. Configuration almost matches as listed on git for hydrolysis. But I am not able to figure out how to get typings/main.d.ts .
I am using VS 2015 update 3. Also TypeScript Toolbox version is 1.0. I even checked with version 1.8 and 2.1 but I am getting same issue.
Also I tried to install dependencies from typings.json manually, but in this case I am getting error with iron-data-table package I have used.
My folder structure is 
![image](https://cloud.githubusercontent.com/assets/24915506/21758714/5482a9fc-d664-11e6-9978-a9bafe6c15ee.png)

**Comment by FredKSchott** [comment]
[Typings](https://github.com/typings/typings) is a way to get 3rd party type definitions. You'll need to run `typings install` to install those types and get a typings/main.d.ts file.

If this is a new project, I'd recommend using polymer-analyzer instead of hydrolysis. It's the newest version of our analyzer and although it is still in beta, it is less buggy and much easier to use.

**Comment by kunal2u** [comment]
Thanks for the reply. Since it is not new project it is not possible to use polymer-analyzer as it would break dependencies. Also i tried to run typings install. But it doesn't install any packages as mentioned in ambientDependencies. Also I changed it to globalDependency and after running it installed dependency in folder inside typings > global > node > index.d.ts. What I need is typings > main.d.ts. As mentioned in this project source I have only one dependency of node in typings.json. Also I don't have package.json . Instead my project has bower.json . When I build the project bower.json dependencies are installed automatically but this doesn't happen in case of typings.json . How to make 'typings run'  execute automatically on Build like bower.json OR is it like that typings.json dependencies are meant to be installed manually / development time only?

**Comment by FredKSchott** [comment]
The part after the "#" is for a commit on github, probably somewhere in the `DefinitelyTyped/DefinitelyTyped` repo. That's all I know.

I'm sorry but I don't know how to help you any further. If you're having trouble with the typings tool, I'd recommend visiting their FAQ (https://github.com/typings/typings) and looking for help there. Our slack channel would also be a good resource if someone else has also run into this problem.

**Comment by kunal2u** [comment]
@FredKSchott This issue not closed. What I need is typings > main.d.ts. As mentioned in this project source I have only one dependency of node in typings.json. After running typings install it is installed dependency in folder inside typings > global > node > index.d.ts . Also it is causing problem with other components. Also how can we search specific commit of the repo, what's the way?
