### ISSUE TITLE
HTML document `<base href="...">` does not influence import scanning.

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-analyzer#436]
Discovered while working on `polymer-bundler` to implement `<base>` tag handling, I discovered that calling `document.getByKind('import')` on my analyzed document, the set returned did not include all the expected transitive dependencies.  The point of disconnect was an imported document that included a `<base>` tag which modified the intent of its href and src attributes etc.

Propose extending the analyzer to make document "base url" a thing different but derived from the document url and properly identify such when `<base>` present in an HTML document.

**Comment by rictic** [comment]
+1

Do you have an example document easily available?

**Comment by usergenic** [comment]
My test is these four documents.
 - Root (no base tag) https://github.com/Polymer/polymer-bundler/blob/master/test/html/base.html
 - Import, has base tag https://github.com/Polymer/polymer-bundler/blob/master/test/html/imports/base.html
 - Nested Import, https://github.com/Polymer/polymer-bundler/blob/master/test/html/imports/base-foo/sub-base.html
 - Nested Nested Import, https://github.com/Polymer/polymer-bundler/blob/master/test/html/imports/super-base.html

**Comment by justinfagnani** [comment]
Good catch.

Seems like in addition to those tests we need a simple root with a base tag.

**Comment by rictic** [comment]
Seems like, since multiple scanners will want this info, this would be a good thing to put on the ParsedHtmlDocument when we produce it

**Comment by justinfagnani** [comment]
Quickly, I think there are two changes to do. First, `ParsedHtmlDocument`, or possibly `ParsedDocument`, should get a `baseUrl` property and a `resolveUrl()` method. Second `HtmlImportScanner` and friends need to use that.

@rictic jinx

**Comment by usergenic** [comment]
I think we fixed this a bunch.  Closing.
