### ISSUE TITLE
failed to resolve Behavior as function()

### ISSUE THREAD

**Issue by eskan** [Polymer/polymer-analyzer#440]
If a behavior is defined like this

`behaviors: [ 
     MyBehavior({ prop : "value"})
],`

analyzer failed with

> [unknown-polymer-behavior] - Unable to resolve behavior `UNKNOWN`

and polymer build failed

**Comment by lassecapel** [comment]
This issue looks a little bit like #432

**Comment by eskan** [comment]
Yes, it does .. except in this case the parser failed to get Behavior name first and fallback to UNKNOW

**Comment by rictic** [comment]
I see two issues here. The first is how to analyze this code, as well as possible. What does your MyBehavior factory do here?

The second issue is that this should not fail polymer build. Can you confirm that the build fails, doesn't just emit a warning? @FredKSchott is this expected?

**Comment by FredKSchott** [comment]
The warning that the analyzer returns for an unknown behavior has severity:`Severity.ERROR`, which `polymer-build` assumes means "something went seriously wrong" and cancels the build itself. We talked earlier about removing this check, and just printing all warnings and continuing to attempt the build until an actual error thrown/rejected/emitted. 

@rictic Knowing a bit more than I do about the possible analyzer warnings/errors, does this still make sense? If most `ERROR` warnings are worth quitting over, we can also keep the check and just ignore `unknown-polymer-behavior` warnings.

**Comment by rictic** [comment]
Gotcha, yeah this should probably be a WARNING not an ERROR. It's one thing if we understand the behavior expression but can't find it, that might should be an ERROR. I'll send over a PR.
