### ISSUE TITLE
Unable to analyze polymer expressions which are not legal javascript

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-analyzer#477]
Notably `{{foo.*}}` and `{{arr.0}}` both work (though the latter only kinda, and by accident).

Currently the expression parser just ignores all such expressions entirely, which can lead to false negatives and false positives in linting.

**Comment by justinfagnani** [comment]
I really think it might be easiest to modify polymer-expressions to support whatever syntax we need. `.*` might already work, but I could easily make it work if it doesn't.

**Comment by boromisp** [comment]
An other example that trips up polymer lint: `{{object.kebab-case}}`
(warning [invalid-polymer-expression] - Only simple syntax is supported in Polymer databinding expressions. BinaryExpression not expected here).
