### ISSUE TITLE
Support escape hatch documentation

### ISSUE THREAD

**Issue by nevir** [Polymer/polymer-analyzer#53]
I.e. documentation not attached to properties we don't special case. We need to be able to insert floating docstrings into the hydrolysis docs

**Comment by atotic** [comment]
This is what we need to support pseudo-element.
From AJ:
```
importParse should operate depth-first
For script nodes, add a filename to the comment list

in jsParse, check for leadingComments in the enter function, add key "comments" to the return value w/ ordered list
in analyze, fold list of js comments into import comments
```

importParse adds all comments to the registry['#comment']
jsParse would have a new comment-finder that finds all the comments.

all comments get combined, and passed to global-tags.js that is called inside Analyzer.annotate

**Comment by rictic** [comment]
We've implemented some of this, and its assumptions are in a 1.x context.
