### ISSUE TITLE
Can Analyzer/AnalysisCache analyze in a mode where it tests for file content changes?

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-analyzer#548]
In an ideal world, `polymer-build` would fork the Analyzer and send a stream of files into Analyzer for analysis and most would be unchanged but a few would be newly minified since the Analyzer last scanned them.

If the Analyzer was able to run in a mode that said it should use `urlLoader.load` and test whether the file contents returned are different than the contents it has in memory for an already scanned document so that it could invalidate the path and rescan it-- that would be great.

Alternately, `polymer-build` might keep a map of paths and digests so it could call the Analyzer with `filesChanged()` after running its own comparisons.

**Comment by rictic** [comment]
Some related thoughts:

* We've like to be able to run the linter in `--watch` mode, where as files change we report them as changed to the analyzer and then rerun the linter. This way you don't need polymer-ide to get really fast linting.
* For both the linter and eventually the analyzer, it would be nice to be able to notice that polymer.json has changed, and change the way we analyze and lint.
* Mostly unrelated: we should really have a way to construct an analyzer from a polymer.json file (or even better, a directory that may contain a polymer.json).

All that said, I think the best short-term option here is likely to keep a map of paths and digests. I think you should be able to do something like `new Map(Array.from(package.getFeatures({kind: 'document', externalToPackage: true})).map(d => [d.url, d.parsedDocument.contents]))` to get a map of all documents and their contents that the analyzer knows about.

**Comment by usergenic** [comment]
I'll close this issue since the solution for Build will be a filename->digest map as you say.
