### ISSUE TITLE
2.0.0 Release

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-analyzer#550]
Tracking issue

**Comment by rictic** [comment]
Should this be a milestone?

**Comment by rictic** [comment]
Should this be 2.0.0?

**Comment by justinfagnani** [comment]
Made 2.0.0, and it should also be a milestone

**Comment by justinfagnani** [comment]
Added 2.0.0 issues to 2.0.0 milestone, inception!

Keeping the issues for discussion around the release and the final steps to release.

**Comment by TimvdLippe** [comment]
Polymer 2.0.0 has been released. Is the analyzer fully 2.0.0 compatible? What features are missing (if any)?

**Comment by justinfagnani** [comment]
This was for 2.0.0 of the Analyzer. We released.
