### ISSUE TITLE
Add a general feature for tracking classes

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-analyzer#563]
Similar to Namespace, and a superclass of both Element and ElementMixin. 

Would be useful in the `call-super-in-callbacks` lint pass. https://github.com/Polymer/polymer-linter/pull/53

Needed to display docs for Dom API.

**Comment by justinfagnani** [comment]
We really need this for the docs. Might bump to high.

**Comment by rictic** [comment]
Taking a shot at this now.
