### ISSUE TITLE
Mixin JSDocs are not recognized on property assignments

### ISSUE THREAD

**Issue by ChadKillingsworth** [Polymer/polymer-analyzer#594]
The analyzer doesn't find the mixin annotation in this case:

```js
/** @mixes MyMixin */ window.MyElement =  class extends MixedElement { }
```

**Comment by ChadKillingsworth** [comment]
For reference, here's the algorithm closure-compiler uses to find JSDoc annotations: https://github.com/google/closure-compiler/blob/5f9c7428a4dc87967883795e28324fc87be1d941/src/com/google/javascript/jscomp/NodeUtil.java#L4394-L4432

**Comment by justinfagnani** [comment]
Thanks for the link!

**Comment by ChadKillingsworth** [comment]
Nice!
