### ISSUE TITLE
Warning underlines have incorrect position if source is indented with tabs.

### ISSUE THREAD

**Issue by coreyfarrell** [Polymer/polymer-analyzer#597]
When a source line is indented with tabs the underline produced by `WarningPrinter.getUnderlinedText` is indented with spaces, causing the underline to have the incorrect indentation compared to the source.

**Comment by coreyfarrell** [comment]
Sorry I didn't link from the PR, this is fixed by https://github.com/Polymer/polymer-analyzer/pull/603

I'm not sure if this ticket should be closed now or if it's being held open for the next release?

**Comment by rictic** [comment]
Our policy is to close on merge.

Thanks again for the fix!
