### ISSUE TITLE
ES6 Getters aren't recognized as properties

### ISSUE THREAD

**Issue by ChadKillingsworth** [Polymer/polymer-analyzer#645]
The analyzer seems to completely ignore ES6 getters - they are not recognized as properties.

We're beginning to switch our code base to use ES6 getters instead of computed properties.

```js
class FooElement extends Polymer.Element {
  static get is() { return 'foo-element'; }

  get otherProp() {
    return 'some value';
  }
}
```

**Comment by rictic** [comment]
I'm gonna do a pass in a bit where I'll recognize property declarations in constructors. Will be a good time to add this in too.

**Comment by baszczewski** [comment]
This lack of functionality affects also: https://github.com/Polymer/polymer-analyzer/issues/329.

**Comment by ChadKillingsworth** [comment]
@baszczewski You need annotations:

```js
/**
 * @polymer
 * @customElement
 */
class FooElement extends Polymer.Element { }
```

**Comment by rictic** [comment]
Alternatively you need to do `customElements.define(FooElement.is, FooElement);` in the same script that you declare `FooElement`.
