### ISSUE TITLE
@mixinFunction doesn't work with function expressions

### ISSUE THREAD

**Issue by ChadKillingsworth** [Polymer/polymer-analyzer#660]
```js
/**
 * @mixinFunction
 * @polymer
 */
function applyOne(Superclass) {
  /**
   * @mixinClass
   * @polymer
   */
  class One extends Superclass {
    one() {}
  }
  return One;
}

/**
 * @mixinFunction
 * @polymer
 */
function applyTwo(Superclass) {
  /**
   * @mixinClass
   * @polymer
   */
  class Two extends Superclass {
    two() {}
  }
  return Two;
}

/**
 * @constructor
 * @extends {Polymer.Element}
 * @appliesMixin applyOne
 * @appliesMixin applyTwo
 */
const BaseElement = applyTwo(applyOne(Polymer.Element));

/**
 * @polymer
 * @customElement
 */
class MyElement extends BaseElement {
  static get is() {
    return 'my-element';
  }
}

customElements.define(MyElement.is, MyElement);
```

Produces warning "Unable to resolve superclass BaseElement"

This is the style required by Closure-compiler. Also, even though #605 talks about using `@appliesMixin {functionRef}`, the annotation only works without the curly braces.

**Comment by justinfagnani** [comment]
You need to move the `@extends {Polymer.Element}`, `@appliesMixin applyOne` and `@appliesMixin applyTwo` annotations to `MyElement`, then it should work.

The Analyzer doesn't even attempt to resolve JS references right now, so it solely relies on annotations on the element class itself to build up the inheritance hierarchy.

As for `@appliesMixin {functionRef}`, oops :) We probably want a separate issue for that.

**Comment by ChadKillingsworth** [comment]
That worked - but highlighted a new problem: function expressions and `@mixinFunction`

```js
/**
 * @mixinFunction
 * @polymer
 */
var applyOne = function(Superclass) {
  /**
   * @mixinClass
   * @polymer
   */
  class One extends Superclass {
    one() {}
  }
  return One;
}

/**
 * @mixinFunction
 * @polymer
 */
var applyTwo = function(Superclass) {
  /**
   * @mixinClass
   * @polymer
   */
  class Two extends Superclass {
    two() {}
  }
  return Two;
}

/**
 * @constructor
 * @extends {Polymer.Element}
 */
const BaseElement = applyTwo(applyOne(Polymer.Element));

/**
 * @polymer
 * @customElement
 * @extends {BaseElement}
 * @appliesMixin applyOne
 * @appliesMixin applyTwo
 */
class MyElement extends BaseElement {
  static get is() {
    return 'my-element';
  }
}

customElements.define(MyElement.is, MyElement);
```

**Comment by ChadKillingsworth** [comment]
nevermind - that does work. I just have the JSDoc attached to the wrong node.

**Comment by arthurevans** [comment]
@justin is this still true? Does every element that uses a mixin need to know (and annotate!) every sub-mixin they incorporate :/?

**Comment by justinfagnani** [comment]
@arthurevans no, `MyElement` in the last example should inherit all the members from mixins applied to `BaseElement`. If it doesn't, that's a bug.

Also, if a mixin composes other mixins, it needs to list them with `@appliesMixin`, but then those properties are inherited by the owner mixin and propagate to its applications.
