### ISSUE TITLE
Style: use Capitalized names and 'new' for constructor-like functions.

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-analyzer#67]
Looking through the code base, I saw this:

`var elFinder = elementFinder();`

`elementFinder` returns an object with methods, it'd be easier, IMO, to follow if it was a standard constructor and instantiated with new:

`var elFinder = new ElementFinder();`

and in the declaration, hang methods off the prototype.

**Comment by atotic** [comment]
elementFinder is a module. It should be imported as uppercase. Will keep in mind when rewriting.

**Comment by justinfagnani** [comment]
In that case elementFinder should follow the normal CommonJS module pattern. So, remove the `elementFinder` function, and do `exports.visitors = visitors; exports.elements = elements;`

**Comment by justinfagnani** [comment]
Looking again though, elementFinder really looks like a class-like thing, since it stores state. I think it should be written as a prototype with constructor.

**Comment by rictic** [comment]
Fixed in 2.0
