### ISSUE TITLE
Properties inherited from behaviors not considered

### ISSUE THREAD

**Issue by andreasanheuser** [Polymer/polymer-analyzer#680]
See e.g. paper-tabs documentation: https://www.webcomponents.org/element/PolymerElements/paper-tabs/elements/paper-tabs

`selected` property is not listed under API.

**Comment by rictic** [comment]
This looks like a webcomponents.org issue, as I see `selected` when I analyze locally.

Repro:

```bash
git clone https://github.com/PolymerElements/paper-tabs.git && cd paper-tabs && bower install && polymer analyze | grep selected
```

**Comment by rictic** [comment]
This issue was moved to webcomponents/webcomponents.org#972
