### ISSUE TITLE
HTML comments on templates are being used as element comments

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-analyzer#689]
See the wonder comment here by @notwaldorf https://www.webcomponents.org/element/PolymerElements/paper-input/elements/paper-input

**Comment by notwaldorf** [comment]
Screenshot for posterity. The comment comes from: https://github.com/PolymerElements/paper-input/blob/master/paper-input.html#L165


<img width="803" alt="screen shot 2017-05-31 at 1 59 15" src="https://cloud.githubusercontent.com/assets/1369170/26653898/857988d6-4609-11e7-9fc5-8df55fc7c18b.png">

**Comment by arthurevans** [comment]
As awesome as this comment is, can we make this a P0 or at least a P0.5 because it looks really, really bad is totally unhelpful to users.

**Comment by rictic** [comment]
Taking a look now.

**Comment by web-padawan** [comment]
might be related to #674, although comments outside of `template`tag (e. g. between groups of HTML imports) are also treated like this.
