### ISSUE TITLE
Event description is not used

### ISSUE THREAD

**Issue by veith** [Polymer/polymer-analyzer#713]
It would be nice if the event description is used instead of the event name. The description of an event is very helpful / important. It is also recommended in the documentation (https://www.polymer-project.org/2.0/docs/tools/documentation#events).

*current output in analysis.json*
```
"events": [
  {
        "type": "CustomEvent",
        "name": "request",
        "description": "request",
        "metadata": {}
   },...
``` 

*current output in iron-doc-element*
``` 
request: CustomEvent
request
```

*desired output*
```
"events": [
  {
        "type": "CustomEvent",
        "name": "request",
        "description": "Fired when a response is received. ",
        "metadata": {}
   },...
``` 
``` 
request: CustomEvent
Fired when a response is received. 
```
 
*example (iron-ajax)*
https://github.com/PolymerElements/iron-ajax/blob/master/iron-ajax.html#L56
https://www.webcomponents.org/element/PolymerElements/iron-ajax/elements/iron-ajax#event-request

**Comment by veith** [comment]
@FredKSchott This is the Issue, we talked about in Kopenhagen

**Comment by davidrleonard** [comment]
# Analyzer event issue

We’re also facing this issue. We’re analyzing our components with polymer-analyzer and passing the resulting data to iron-doc-element for our documentation on predix-ui.com. But the event descriptions are not coming through.

Here’s an example event I want to parse inside one of my Polymer components:

```js
    /**
     * Fired when the search input field's content changes.
     * @event px-typeahead-search-input-change
     */
```

I think I found the problem:

After a file is with a Polymer component is parsed, its bits of jsdoc attached to AST nodes are peeled off and prepped for analysis. The events found in a Polymer component are parsed here in `getEventComments`:

https://github.com/Polymer/polymer-analyzer/blob/18d68db38f927c72f59ba7160a0a3a0f82838ddb/src/javascript/esutil.ts#L124-L145

On line 140, the jsdoc `comment` for an event is sent to `jsdoc.parseJsdoc`:

https://github.com/Polymer/polymer-analyzer/blob/18d68db38f927c72f59ba7160a0a3a0f82838ddb/src/javascript/jsdoc.ts#L27-L44

parseJsdoc uses the `doctrine.parse` function to parse stuff. What comes back from doctrine looks like this:

```json
{
  "description": "Event fired when search input field changes.\n",
  "tags": [
    {
      "title": "event",
      "description": "px-typeahead-search-input-change"
    }
  ]
}
```

The `getEventComments` function then sends that doctrine object to the `annotateEvent` function as the `annotation`:

https://github.com/Polymer/polymer-analyzer/blob/18d68db38f927c72f59ba7160a0a3a0f82838ddb/src/polymer/docs.ts#L73-L106

This is where things go belly-up. This function got doctrine’s `annotation` from up above. And the event description is there, at `annotation.description`. That annotation is sent to `jsdoc.getTag`, which plucks the sole tag in the `annotation.tags` array out and returns it the `eventTag` variable. Now `eventTag` is:

```json
    {
      "title": "event",
      "description": "px-typeahead-search-input-change"
    }
```

When the event description is prepped to send to the user on 86, the `eventTag.description` is used first, and if it doesn’t exist, `annotation.description` is used. The eventTag description is wrong ("px-typeahead-search-input-change”), and the annotation description is right ("Event fired when search input field changes.\n”). I’m guessing there’s a good reason to use the eventTag description before the annotation description, but if we just flip this on line 86 it then everything should work fine:

```
    description: annotation.description || (eventTag && eventTag.description),
```

Hope this helps.

**Comment by veith** [comment]
Works when you write it the following way:
```
/**
 * @event awesome-change
 *
 * Fired when `element` changes its awesomeness level.
 */
```

The documentation is wrong 
https://www.polymer-project.org/2.0/docs/tools/documentation#events
```

/**
 * Fired when `element` changes its awesomeness level.
 *
 * @event awesome-change
 * @param {number} newAwesome New level of awesomeness.
 */
```

**Comment by davidrleonard** [comment]
This is a pretty big breaking change for us. Hydrolysis used to treat these as valid jsdoc comments and we have many events documented throughout our component system this way:

```
/**
 * Fired when `element` changes its awesomeness level.
 *
 * @event awesome-change
 * @param {number} newAwesome New level of awesomeness.
 */
```

The jsdoc website says this format is valid: http://usejsdoc.org/tags-event.html

See also #836 which points to a core Polymer component that uses the comment-first-in-the-jsdoc style for event docs. I believe there are more Polymer components that use this format, as many event descriptions for custom events disappeared off webcomponents.org a bit back.

Any chance we can get this re-opened and addressed? Help would be much appreciated, thanks!
