### ISSUE TITLE
Feature request: infer void return type

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-analyzer#753]
A function with no `return` statements (or only return statements with no argument) in it, which is neither a generator or an async function, can be inferred to have a return type of void.

Many functions on elements have a void return type, so this could save a lot of typing.

Request came from slack

**Comment by 43081j** [comment]
as in #826, we can probably close this because it seems we all think its better to be explicit. no guesswork

**Comment by rictic** [comment]
yeah.. makes sense

**Comment by aomarks** [comment]
We decided to implement this after all, as our elements very consistently omit `@return {void}`, because Closure accepts omission of `@return` as equivalent, which causes a very large number of `any`s to be emitted by gen-typescript-declarations.
