### ISSUE TITLE
URL resolvers should produce absolute URLs, including protocol

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-analyzer#765]
Pros:
  - Would be a very clear and unambiguous model, as we'd have absolute `file://` urls for the default use case
  - I think this would help us better deal with use cases where unresolved and resolved urls are very different (e.g. the internal-to-google case)
  - This will definitely help us better deal with use cases where all resources are remote, like the Polymer Designer case.
  - I've used `file://` urls a lot in the editor service, and they are both powerful and can be made to work consistently cross-platform easily.
  - If we used whatwg urls it would let us give feedback to the WHATWG URL spec.
  - Would let us more easily handle a mixture of local files and remote resources in a project, solving cases like Polymer/polymer-editor-service#95
  - Node's core `fs` module is [working on supporting whatwg urls for filesystem APIs](https://nodejs.org/api/fs.html#fs_whatwg_url_object_support), and starting in 7.0 [whatwg urls are the preferred url objects](https://nodejs.org/api/url.html#url_the_whatwg_url_api). 
  - Would make the division of responsibility between url resolvers and url loaders clearer.

Cons:
  - Resolved URLs would be longer when printed out.
  - Significant migration cost.

**Comment by rictic** [comment]
There's a maintained library for whatwg-urls here: https://www.npmjs.com/package/whatwg-url

**Comment by rictic** [comment]
Open question:
  * Do we use full URL objects, or just require absolute URLs as strings?
    * We use ResolvedUrls as keys in a number of maps, so we would need a canonicalization step if we kept them as objects.
    * URL objects are mutable, which would could really cause problems in places where we're using them as keys in maps
    * If we kept them as strings we'd do a decent amount of re-parsing them over and over again

**Comment by justinfagnani** [comment]
Summary of some chat discussion:

 * `URL`s are hard to use as Map and Set keys, we'd have to make a Map subclass
 * The browser has well-defined semantics for interpreting strings as URLs, and we try to match those, we should keep doing that while supporting external URLs
 * Resolving URLs requires a base URL to resolve from
 * Resolving npm package names requires a base path as well
 * We should update the UrlResolver interface to require a base URL
 * We might want to get rid of `FileRelativeUrl` and `PackageRelativeUrl` branded string types

**Comment by rictic** [comment]
Core changes needed:
  * A ResolvedURL is redefined to mean a complete URL `file:///path/to/foo` or `https://example.com/file.html`. 
    * Maybe this is a URL object in combination with clever Map/Set subclasses (key insight: internally key by URL#toString(), but expose the API in terms of URL objects, avoids the interning problem), or maybe we continue using strings.
  * This means that UrlResolvers will take on more responsibility, and UrlLoaders will become much simpler.
  * UrlResolvers will need a new method with signature: `(urlFromDocument: FileRelativeUrl, baseUrl: ResolvedUrl): ResolvedUrl`, and this should be the only way of going from a `FileRelativeUrl` to a `ResolvedUrl`.
