### ISSUE TITLE
Declaring class inside function makes `polymer build` fail.

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer-analyzer#832]
_From @kkimdev on December 25, 2017 3:17_

### Description
On Polymer 3.0, declaring class inside function makes `polymer build` fail.

#### Steps to Reproduce

1. Follow https://www.polymer-project.org/blog/2017-08-23-hands-on-30-preview
2. edit myapp.js so that
```javascript
// ...
  constructor() {
    super();
    class Foo{};
    this.name = '3.0 preview';
  }
// ...
```

#### Expected Results
`polymer build` succeeds.

#### Actual Results
`polymer build` fails.
```
polymer build
info:    Clearing build/ directory...
info:    (default) Building...


    <script type="module" src="src/my-app.js"></script>
                              ~~~~~~~~~~~~~~~

index.html(9,30) error [could-not-load] - Unable to load import: Cannot read property 'properties' of null
error:   Promise rejection: Error: 1 error(s) occurred during build.
error:   Error: 1 error(s) occurred during build.
    at BuildAnalyzer._done (/usr/local/share/.config/yarn/global/node_modules/polymer-build/lib/analyzer.js:262:36)
    at BuildAnalyzer.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/polymer-build/lib/analyzer.js:222:26)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/polymer-build/lib/analyzer.js:17:58)
    at <anonymous>
```

### Versions
$ polymer --version
1.5.7

_Copied from original issue: Polymer/polymer#5005_

**Comment by TimvdLippe** [comment]
_From @kkimdev on December 25, 2017 3:18_

@farQtech

**Comment by rictic** [comment]
Standalone repro:
```html
<base href="https://polygit.org/polymer+:master/webcomponents+:master/shadycss+webcomponents+:master/components/">
<script src="webcomponentsjs/webcomponents-lite.js"></script>
<link rel="import" href="polymer/polymer.html">

<hello-world></hello-world>

<script>
  window.addEventListener('WebComponentsReady', () => {
    class HelloWorld extends Polymer.Element {
      constructor() {
        super();
        class Foo {};
      }
      static get is() {return 'hello-world';}
    };
    customElements.define(HelloWorld.is, HelloWorld);
  });
</script>
```

Repro on playground (temporary location, this link will break): https://polymer.github.io/analyzer-playground/?input=%3Cbase+href%3D%22https%3A%2F%2Fpolygit.org%2Fpolymer%2B%3Amaster%2Fwebcomponents%2B%3Amaster%2Fshadycss%2Bwebcomponents%2B%3Amaster%2Fcomponents%2F%22%3E%0A%3Cscript+src%3D%22webcomponentsjs%2Fwebcomponents-lite.js%22%3E%3C%2Fscript%3E%0A%3Clink+rel%3D%22import%22+href%3D%22polymer%2Fpolymer.html%22%3E%0A%0A%3Chello-world%3E%3C%2Fhello-world%3E%0A%3Chello-world+place%3D%22Oakland%22%3E%3C%2Fhello-world%3E%0A%0A%3Cscript%3E%0A++window.addEventListener%28%27WebComponentsReady%27%2C+%28%29+%3D%3E+%7B%0A++++class+HelloWorld+extends+Polymer.Element+%7B%0A++++++constructor%28%29+%7B%0A++++++++super%28%29%3B%0A++++++++class+Foo+%7B%7D%3B%0A++++++%7D%0A++++++static+get+is%28%29+%7Breturn+%27hello-world%27%3B%7D%0A++++%7D%3B%0A++++customElements.define%28HelloWorld.is%2C+HelloWorld%29%3B%0A++%7D%29%3B%0A%3C%2Fscript%3E%0A

**Comment by rictic** [comment]
I suspect that this is because we use local state and key off entering/exiting classes in the ast walker without using a stack. Honestly I wish that we didn't key off exiting at all, and just did all the analysis directly on the entered class ast object. I think this is just the tip of an iceburg of bugs if we keep keying off entering and exiting.

**Comment by rictic** [comment]
Also this is true for Polymer 2 as well
