### ISSUE TITLE
UrlResolver#relative should have option to return undefined

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-analyzer#847]
Generally speaking `analyzer.urlResolver.relative('file:///my/filesystem/details/something.html')` should never be returning a value like `file:///my/filesystem/details/something.html`.  In the case where it does, it would possibly be better to simply return undefined, paving the way for a fall-thru mechanism.

This is important especially in a `MultiUrlResolver` scenario containing multiple package URL resolvers or redirection resolvers, for example, where there currently exists no mechanism for a resolver to elect to produce an appropriate relative URL or opt out if the resolved URL is outside its jurisdiction.

Right now `polymer-bundler` is working around this by constructing a `getPackageRelativeUrl()` [function of its own](https://github.com/Polymer/polymer-bundler/pull/626/files#diff-67bf78febcf9325e0a0adf8f6ef8a937R214) but it would be nicer just ask the resolver for the `relative()` value of a resolved url and correspond nearly symmetrically to `resolve()`.

**Comment by rictic** [comment]
Hm, interesting. When a resolver can't turn a url into a relative URL it should return the URL untouched. Maybe MultiUrlResolver could use that as a signal to try the next resolver?

**Comment by usergenic** [comment]
Today I decided to deal with my issue for the `MultiUrlResolver` needing a fall-thru mechanism for `relative()` by simply having its `relative()` method figure out which resolver to delegate the `relative()` call to by finding out which one would return a ResolvedUrl back when `resolve()` was called with the destination URL.

**Comment by usergenic** [comment]
That was in #851 so I think I'll close this issue for now because changing `relative()` to return undefined is actually kind of an obnoxious amount of work for unclear benefit now.
