### ISSUE TITLE
import `./foo` doesn't convert to `./foo.js`

### ISSUE THREAD

**Issue by keanulee** [Polymer/polymer-analyzer#921]
Need to use node resolution algorithm for resolving relative modules - `./foo` could be `./foo.js` or `./foo/index.js`. Affects polyserve.

cc @usergenic

**Comment by frankiefu** [comment]
cc @justinfagnani

**Comment by aomarks** [comment]
or `./foo.json` so I hear

**Comment by jsilvermist** [comment]
What are the rules on precedence?

**Comment by aomarks** [comment]
Note to self: this same issue needs to be fixed in the polymer-build bare specifier babel plugin.

**Comment by aomarks** [comment]
> What are the rules on precedence?

We just call Node's resolve (actually browserify/resolve) so, whatever that says.

**Comment by justinfagnani** [comment]
This is fixed in polymer-build and polyserve, but we need to consolidate the logic into one place in Analyzer.
